Imports System.Text
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports CSVMerge

<TestClass()> Public Class UT_ReadHeader

    <TestMethod()> Public Sub ReturnNothing()
        Dim result = FileProcess.ReadHeader("asdasd")

        Assert.AreEqual(Nothing, result)
    End Sub

    <TestMethod>
    Public Sub ReturnHeader()
        Dim result = FileProcess.ReadHeader("D:\TEST\cqs\test\1.csv")

        Assert.AreEqual("""BETNR"";""REKDNAME"";""USTID"";""KUNDENAME123"";""BELEGNR"";""BELEGDATUM"";""AUFTRAGSNR"";""SUBAUFTRAGSNR"";""AUFTRAGSART"";""AUFTRAGSARTTYP"";""AUFTRAGSART"";""FAHRGESTELLNR"";""AUFTRAGSARTTYP"";""FUNKTION"";""BEZEICHNUNG"";""IDENTIFIER"";""GESAMTMENGEAUFPOS"";""ERLOES"";""NACHLASS"";""LAGERWERT"";""RABATTPROZ"";""HOMOGENEGRP"";""RABATTGRP"";""FABRIKATKZ"";""VERRFABRIKATKZ"";""FABRIKATGRP"";""WARENART"";""VERRFABRIKATKZ"";""FABRIKATKZ"";""ASIGURATOR"";""ABNEHMERGRP"";""KMSTAND"";""AUFTRAGSDATUM"";""ABNEHMERGRP"";""FZGMODELL"";""FZGMODELLBEZ"";""MODCODE"";""MODJAHR"";""MOTORNR"";""NORMALRAB"";""ABTEILUNG_BH"";""UPE"";""ZEITEINHEITENFUERITAREAB"";""REFERENZVERRECHSATZ"";""REFERENZVERRECHSATZKZ"";""SOLLZEITEINHEITEN"";""VERRECHNUNGSSATZ"";""VERRECHSATZKZ"";""VERKFSTUNDEN"";""MENGE"";""LACKMATEINHEITEN"";""LACKART"";""FIXPREISKZ_ARBEIT"";""PAKETNR"";""SPARPAKET"";""ABTEILUNG_MECH"";""REFERENZSOLLZEITEINHEITEN"";""AMTKENNZGEGNER"";""STEUERLBEH"";""STEUERLBEHLIEF"";""FIXPREISPAKET"";""BERECHPOSART"";""MANDANTNR"";""MODULNR"";""FAKTLFDNR"";""KOSTENSTELLE"";""KOMBIKZ"";""AUFTRAGSTYP"";""STEUERLBEH"";""GESCHFALL"";""VERSICHGPTNR"";""LEASINGGPTNR"";""ZAHLUNGSMITTEL"";""ZIELTAGENETTO"";""GWLANTRAGSNR"";""STORNOKZ"";""KASKOKZ"";""POLIZZENNR"";""GPTNRKUNDE"";""FZGID"";""GPTNRKDB"";""NORAMELDUNG"";""ABNGRPVERGBER"";""NORASTATUS"";""ABNEHMERGRPNORA"";""LEISTUNGSDATUM"";""USTIDNORA"";""VERSICHSYSTEM"";""VERSICHUEBERTRAGEN"";""RABGRP"";""REFNRGUTSCHRIFT"";""REFNRSTORNO"";""RECHNRART"";""RABTEXT"";""PROZFL"";""PROZFMAT"";""GROSSABNNR"";""AUFTRAGSKATEGORIE"";""FAKTURIERT"";""GROSSABNNRKUNDE"";""BELEGNRART"";""KASSAABSCHLUSSLFDNR"";""VERRECHNUNGSGRAD"";""REKDKZ"";""ECHTERECHNUNG"";""ZUSATZMERKMAL"";""MANDANTNR"";""MODULNR"";""VERRECHNUNGSART"";""BELEGNR"";""BELEGDATUM"";""USTPROZ"";""KOMBIKZ"";""GPTNRMECHANIKER"";""HAUPTLIEFGPTNR"";""NORABONUS"";""ZUBEHOERART"";""ZUBANALYSEGRP"";""ALTFZGRABATTPROZ"";""HAUSPOSITIONJN"";""VERRECHNUNGSGRAD"";""VKURSPRUNG"";""SOLLUMSATZ"";""ABTEILUNG_AP"";""NEUKUNDE"";""LEASFIRMANAME1"";""LEASFIRMANAME3"";""VERSICHERUNGGPTNR"";""VERSICHERUNGSAGENT"";""VERSKONTROLLNR"";""COD_FISCAL_ASIGURATOR"";""STEUERNUMMER"";""DEPARTAMENT""", result)
    End Sub
End Class